server:
  port: 8081
spring:
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  messages:
    basename: i18n/login
